### ISSUE TITLE
Permalink url has strange tag

### ISSUE THREAD

**Issue by mashirozx** [mAAdhaTTah/wordpress-github-sync#200] opened 2018-04-22 09:56 UTC
There's a permalink using the url to the original WordPress posts, which not work normally on Jekyll. 
I mean there's a permalink:
```
---
ID: 2886
post_title: CNAME 接入 Cloudflare CDN
author: Mashiro
post_excerpt: '其实就是骗到一个 Cloudflare 的 Partner 资格而已啦 :bbd:'
layout: post
permalink: >
  https://2heng.xin/2018/04/20/cname-cloudflare-free-cdn/
published: true
post_date: 2018-04-20 16:02:56
---
```

I don't know why I got the `>`, but not all posts get wrong, there are some posts shown normally, like:

```
---
ID: 2793
post_title: 使用 Pillow 按色彩范围抠图
author: Mashiro
post_excerpt: ""
layout: post
permalink: https://2heng.xin/2018/04/05/python-pil/
published: true
post_date: 2018-04-05 09:34:32
---
```

The result is you cannot open the post links although they are shown on posts list. Actually you can see it here: <https://www.mashiro.top/posts/>, just the first link not work but the second works fine.

Anyway great plugin, looking forward to the fix, thanks! :grin:

**Comment by mashirozx** [comment] 2018-04-22 10:31
Another problem, it not work with some UTF-8 characters.
For example, the url <https://2heng.xin/2018/02/07/大塚愛-aio-piano/> will be encoded to <https://2heng.xin/2018/02/07/%e5%a4%a7%e5%a1%9a%e6%84%9b-aio-piano/>, this lead to the incorrect title in Jekyll:
![image](https://user-images.githubusercontent.com/16148054/39093983-105f8246-465b-11e8-8286-d9f26d2e74ca.png)
There's PHP function to solve this: <http://php.net/manual/en/function.urldecode.php>
For example:
```PHP
<?php
$str = "w3cschool%E4%BD%A0%E5%A5%BD";
echo urldecode($str);
?>
```

**Comment by mashirozx** [comment] 2018-04-22 11:35
And just find another HTML tag mistake in the backup version:
![image](https://user-images.githubusercontent.com/16148054/39094581-29d0317c-4664-11e8-8fe8-138be9b4253b.png)
`</ol>` tag shouldn't include any attribute.

This part originally write in Markdown on WordPress:
```md
1. balabala
2. balabala
```
Maybe it's a good idea to backup the original Markdown content directly cause Jeklly has a even better support for Markdown than WordPress. :-)

**Comment by mAAdhaTTah** [comment] 2018-04-23 01:11
The issue with Jekyll is a duplicate of #184.

WPGHS doesn't actually handle the Markdown content at all. That's the responsibility of whatever Markdown plugin you're using. We just export whatever we're given, so you should file an issue with them.

**Closed as completed by mAAdhaTTah** 2018-04-23 01:11 UTC

**Comment by mashirozx** [comment] 2018-04-23 03:52
Got it
