### ISSUE TITLE
Draft posts modification time

### ISSUE THREAD

**Issue by jonocarroll** [mAAdhaTTah/wordpress-github-sync#140] opened 2016-05-22 11:44 UTC
Firstly, thank you for this plugin. It's thoroughly amazing and I'm loving that I can now edit my draft posts in emacs, have everything saved offsite in a repo, and can share edits with others. It's exactly what I needed.

A small issue I noticed; posts marked as drafts (I used the extra instructions to allow sync of draft posts) all got their modification times updated to the time of the last sync (import all or the initial commit). I don't know if the schema has a way to handle the actual modification time, but I thought I'd mention it. Not a major issue as the posts are drafts and updating an individual draft post updates its time correctly.

Please close if not a genuine issue.

**Comment by mAAdhaTTah** [comment] 2016-05-22 14:50
It should have the correct modification time, so I'll have to take a look into it.

**Comment by ytjohn** [comment] 2017-05-07 13:39
I know this is an old bug, but I encountered this same issue. I recently set this up to import an existing markdown blog. I went through the markdown files to make sure I had the correct post_date in the yaml frontmatter, but when I imported, the plugin made all of the posts published at the time of the import. It made it my most productive blogging day - roughly 50 posts within less than a minute. I was going through post by post doing quick edit to correct the publish date. If I had more posts, I would have had probably wrote a tool.

**Comment by mAAdhaTTah** [comment] 2017-05-07 14:22
Bah, that's not a good experience. I should really figure out what's going on here.

**Comment by ytjohn** [comment] 2017-05-07 14:45
If it helps, here are my source posts .  

https://github.com/ytjohn/yourtech-us/tree/42dc2a28f9f784c6f837585de613166733b0f361/raw

And here is a sync operation:

https://github.com/ytjohn/yourtech-us/commit/b56bcfc9f81fa576af872fad52a32c381b5f5232

**Comment by mAAdhaTTah** [comment] 2017-07-02 18:43
Looking into the code & WordPress, it kinda looks like this is on WordPress's end. If I'm not mistaken, `post_date` doesn't get set until the post has been published. Once the post is published, the `post_date` no longer gets changed, either in WP or WPGHS. Does that conform with your experiences?

@ytjohn How/why was this file changed from `raw` to `_drafts`? Were you using `raw` as your drafts location? If these files were imported as drafts from the `raw` folder, then given the above, the `post_date` changing would be expected, I think.

**Comment by ytjohn** [comment] 2017-07-02 20:52
Looking back at this, it looks like  [post_date](https://developer.wordpress.org/reference/functions/wp_insert_post/) needs to be read from the file being imported and added to the args that get used by wp_insert_post. If post_date is not set, WP defaults to today's date. If it is set, then the post_date is set to that value.  Though I suppose wordpress might have a more stringent format for the date than I am using.

> You can set the post date manually, by setting the values for ‘post_date’ and ‘post_date_gmt’ keys. You can close the comments or open the comments by setting the value for ‘comment_status’ key.

Looking at the example code on that page, I see: `$postarr['post_date'] ) || '0000-00-00 00:00:00'`, so I will try that next and let you know.

FYI - yes, I placed the markdown files I wanted to import into the raw folder. WPGHS takes those files, injects them into wordpress, and then places them into _drafts or _posts depending on the `published` flag.  I had tried it in previous variants using the _drafts/_posts folders. IIRC, The files simply get rewritten in place or renamed to match the exact post title. It made more sense to put them in a raw or import folder and let WPGHS migrate them to the final folder destination.

**Comment by ytjohn** [comment] 2017-07-02 21:00
Ok, here goes the test. In fact, looking back, I was using the same date format already.

You can see the WGHS  operation [here](https://github.com/ytjohn/yourtech-us/commit/4b67598eba64b3f44778e69f3e1873850ac8099f). 

My best guess is that WPGHS is not reading the post_date and adding it to the $args that are utilized by wp_insert_post.

1. Create new file in _posts:

````
---
post_title: "test post 001 ignore"
author: ytjohn
post_date: 2017-04-20 19:00:00
post_excerpt: "a test post to be ignored"
layout: post
published: true
---

this is a test post for testing wpghs.
````

2. Once I save that, WPGHS will import the post, and recreate the file. 

```
---
ID: 506
post_title: test post 001 ignore
author: ytjohn
post_date: 2017-07-02 20:55:43
post_excerpt: ""
layout: post
permalink: >
  https://www.yourtech.us/2017/test-post-001-ignore
published: true
---
this is a test post for testing wpghs.
```

**Comment by ytjohn** [comment] 2017-07-02 21:01
As an afterthough, I put the post_date in quotes. [Same behavior](https://github.com/ytjohn/yourtech-us/commit/877f5672a0d550c1d7e703d402d53ef38eae5d5e).

**Comment by mAAdhaTTah** [comment] 2017-07-02 21:20
> If post_date is not set, WP defaults to today's date. If it is set, then the post_date is set to that value.

Does WP do this to published posts too?

> Once I save that, WPGHS will import the post, and recreate the file.

The reason it's recreating the file is the filename of the created post and the filename to export to doesn't match, so it updates the repo so they match. If you created the file with the correct date & slug matching the `post_title`, it should just update the file with the post id and whatever other information is missing.

What I'm suggesting is the `post_date` changing matches the behavior of editing a post via wp-admin; the `post_date` is updated every time you save there too, so WPGHS does the same thing.

Actually, what we should do is not export it unless the post is published. Since the `post_date` means "the time the post was published", a draft post shouldn't have a `post_date`.

Let me know if creating a file with the correct filename works to not recreate the file, but it should still update it with some extra information.

**Comment by mAAdhaTTah** [comment] 2017-07-02 21:25
ping @jonocarroll @ytjohn See #180.

**Comment by ytjohn** [comment] 2017-07-02 21:26
If the filename is "correct", with today's date, it will not be renamed.

```
 ---
 +ID: 511
  post_title: test post 003 ignore
 -post_date: 2017-07-02 21:00:58
 +author: ytjohn
 +post_date: 2017-07-02 21:22:49
 +post_excerpt: ""
  layout: post
 +permalink: >
 +  https://www.yourtech.us/2017/test-post-003-ignore
  published: true
  ---
 -this is a test post for testing wpghs.
 +this is a test post for testing wpghs.
```

**Comment by ytjohn** [comment] 2017-07-02 21:26
Ok, saw #180 - I think the confusion is this original bug was about modification_time and not post_date. I'm going to create a new issue specific to that.

**Comment by mAAdhaTTah** [comment] 2017-07-02 21:30
> If the filename is "correct", with today's date, it will not be renamed.

Ok, cool, that's otherwise as expected. #180 removes `post_date` from unpublished posts, which seems like more correct behavior.

> I think the confusion is this original bug was about modification_time and not post_date.

Oh... rereading the original post, that is correct. Although, @jonocarroll, I'm not entirely sure what the problem is; `post_modified` should be updated to when the sync happened, as that was when the post was last modified. If it's an issue with `post_date`, then #180 solves it. Either way, I think that'll close this out.

**Comment by ytjohn** [comment] 2017-07-02 21:35
@mAAdhaTTah I created #181 to break my issue out from the rest of this.

**Closed** 2017-07-02 21:47 UTC
Labels: bug

**Comment by jonocarroll** [comment] 2017-07-02 22:58
@mAAdhaTTah my problem was that I had old drafts. When I *first* sync, these drafts have their `post_modified` times updated despite not really being updated, just synced.
